

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["egui_node_graph", "osint-graph", "osint-graph-backend", "osint-graph-shared"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"


[workspace.dependencies]
serde = { version = "^1.0" }
egui = "0.25.0"
anyhow = "1.0"
eframe = { version = "0.25.0", features = ["persistence"] }

# [lib]
# crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 2 # fast and small wasm
