[package]
version.workspace = true
edition = { workspace = true }

name = "osint-graph-backend"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
